/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simplepaint;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.*;
/**
 *
 * @author Himanshu
 */
public class PaintWindow extends javax.swing.JFrame {
int mouseX,mouseY,movX,movY,size,eraserRadius;
Graphics2D g;
    /**
     * Creates new form PaintWindow
     */
    public PaintWindow() {
        initComponents();
        size=1;
        eraserRadius=5;
        g=(Graphics2D)paintPanel.getGraphics();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tools = new javax.swing.ButtonGroup();
        paintPanel = new javax.swing.JPanel();
        Pencil = new javax.swing.JRadioButton();
        Line = new javax.swing.JRadioButton();
        Circle = new javax.swing.JRadioButton();
        Rectangle = new javax.swing.JRadioButton();
        Oval = new javax.swing.JRadioButton();
        FillCircle = new javax.swing.JRadioButton();
        FillRectangle = new javax.swing.JRadioButton();
        FillOval = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        BrushSize = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        Eraser = new javax.swing.JRadioButton();
        c204204255 = new javax.swing.JButton();
        c204255255 = new javax.swing.JButton();
        c0204204 = new javax.swing.JButton();
        c255255255 = new javax.swing.JButton();
        c255204255 = new javax.swing.JButton();
        c255204204 = new javax.swing.JButton();
        c1255204204 = new javax.swing.JButton();
        c255255204 = new javax.swing.JButton();
        c204255204 = new javax.swing.JButton();
        c1204255204 = new javax.swing.JButton();
        c204204204 = new javax.swing.JButton();
        c102255255 = new javax.swing.JButton();
        c153153255 = new javax.swing.JButton();
        c255153255 = new javax.swing.JButton();
        c255102102 = new javax.swing.JButton();
        c255204153 = new javax.swing.JButton();
        c255255153 = new javax.swing.JButton();
        c102255102 = new javax.swing.JButton();
        c153255204 = new javax.swing.JButton();
        c153153153 = new javax.swing.JButton();
        c102204255 = new javax.swing.JButton();
        c204102255 = new javax.swing.JButton();
        c25551255 = new javax.swing.JButton();
        c2555151 = new javax.swing.JButton();
        c255153102 = new javax.swing.JButton();
        c255255102 = new javax.swing.JButton();
        c02550 = new javax.swing.JButton();
        c102255204 = new javax.swing.JButton();
        c102102102 = new javax.swing.JButton();
        c051255 = new javax.swing.JButton();
        c2040204 = new javax.swing.JButton();
        c1530102 = new javax.swing.JButton();
        c255051 = new javax.swing.JButton();
        c25515351 = new javax.swing.JButton();
        c25525551 = new javax.swing.JButton();
        c02040 = new javax.swing.JButton();
        c0255204 = new javax.swing.JButton();
        c000 = new javax.swing.JButton();
        c051102 = new javax.swing.JButton();
        c1020102 = new javax.swing.JButton();
        c102051 = new javax.swing.JButton();
        c204051 = new javax.swing.JButton();
        c2041020 = new javax.swing.JButton();
        c2552550 = new javax.swing.JButton();
        c01530 = new javax.swing.JButton();
        airBrush = new javax.swing.JRadioButton();
        text = new javax.swing.JRadioButton();
        setBackground = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuNew = new javax.swing.JMenuItem();
        MenuExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        paintPanel.setBackground(new java.awt.Color(255, 255, 255));
        paintPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                paintPanelMouseDragged(evt);
            }
        });
        paintPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                paintPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                paintPanelMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout paintPanelLayout = new javax.swing.GroupLayout(paintPanel);
        paintPanel.setLayout(paintPanelLayout);
        paintPanelLayout.setHorizontalGroup(
            paintPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        paintPanelLayout.setVerticalGroup(
            paintPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        getContentPane().add(paintPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 720, 510));

        Pencil.setBackground(new java.awt.Color(0, 0, 0));
        Tools.add(Pencil);
        Pencil.setForeground(new java.awt.Color(255, 255, 255));
        Pencil.setText("Pencil");
        getContentPane().add(Pencil, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 54, -1, -1));

        Line.setBackground(new java.awt.Color(0, 0, 0));
        Tools.add(Line);
        Line.setForeground(new java.awt.Color(255, 255, 255));
        Line.setText("Line");
        getContentPane().add(Line, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 95, -1, -1));

        Circle.setBackground(new java.awt.Color(0, 0, 0));
        Tools.add(Circle);
        Circle.setForeground(new java.awt.Color(255, 255, 255));
        Circle.setText("Circle");
        getContentPane().add(Circle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 136, -1, -1));

        Rectangle.setBackground(new java.awt.Color(0, 0, 0));
        Tools.add(Rectangle);
        Rectangle.setForeground(new java.awt.Color(255, 255, 255));
        Rectangle.setText("Rectangle");
        getContentPane().add(Rectangle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 177, -1, -1));

        Oval.setBackground(new java.awt.Color(0, 0, 0));
        Tools.add(Oval);
        Oval.setForeground(new java.awt.Color(255, 255, 255));
        Oval.setText("Oval");
        getContentPane().add(Oval, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 54, -1, -1));

        FillCircle.setBackground(new java.awt.Color(0, 0, 0));
        Tools.add(FillCircle);
        FillCircle.setForeground(new java.awt.Color(255, 255, 255));
        FillCircle.setText("Filled Circle");
        getContentPane().add(FillCircle, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 95, -1, -1));

        FillRectangle.setBackground(new java.awt.Color(0, 0, 0));
        Tools.add(FillRectangle);
        FillRectangle.setForeground(new java.awt.Color(255, 255, 255));
        FillRectangle.setText("Filled Rectangle");
        getContentPane().add(FillRectangle, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 136, -1, -1));

        FillOval.setBackground(new java.awt.Color(0, 0, 0));
        Tools.add(FillOval);
        FillOval.setForeground(new java.awt.Color(255, 255, 255));
        FillOval.setText("Filled Oval");
        getContentPane().add(FillOval, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 177, -1, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tools");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 22, -1, -1));

        BrushSize.setBackground(new java.awt.Color(0, 0, 0));
        BrushSize.setForeground(new java.awt.Color(255, 255, 255));
        BrushSize.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Size 1", "Size 2", "Size 3", "Size 4", "Size 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        BrushSize.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        BrushSize.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                BrushSizeValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(BrushSize);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 140, 82));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Brush Size :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        Eraser.setBackground(new java.awt.Color(0, 0, 0));
        Tools.add(Eraser);
        Eraser.setForeground(new java.awt.Color(255, 255, 255));
        Eraser.setText("Eraser");
        getContentPane().add(Eraser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 218, -1, -1));

        c204204255.setBackground(new java.awt.Color(204, 204, 255));
        c204204255.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c204204255ActionPerformed(evt);
            }
        });
        getContentPane().add(c204204255, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 20, 20));

        c204255255.setBackground(new java.awt.Color(204, 255, 255));
        c204255255.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c204255255ActionPerformed(evt);
            }
        });
        getContentPane().add(c204255255, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 20, 20));

        c0204204.setBackground(new java.awt.Color(0, 204, 204));
        c0204204.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c0204204ActionPerformed(evt);
            }
        });
        getContentPane().add(c0204204, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 520, 20, 20));

        c255255255.setBackground(new java.awt.Color(255, 255, 255));
        c255255255.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c255255255ActionPerformed(evt);
            }
        });
        getContentPane().add(c255255255, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 20, 20));

        c255204255.setBackground(new java.awt.Color(255, 204, 255));
        c255204255.setForeground(new java.awt.Color(255, 204, 255));
        c255204255.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c255204255ActionPerformed(evt);
            }
        });
        getContentPane().add(c255204255, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 20, 20));

        c255204204.setBackground(new java.awt.Color(255, 204, 204));
        c255204204.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c255204204ActionPerformed(evt);
            }
        });
        getContentPane().add(c255204204, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, 20, 20));

        c1255204204.setBackground(new java.awt.Color(255, 204, 204));
        c1255204204.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1255204204ActionPerformed(evt);
            }
        });
        getContentPane().add(c1255204204, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 20, 20));

        c255255204.setBackground(new java.awt.Color(255, 255, 204));
        c255255204.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c255255204ActionPerformed(evt);
            }
        });
        getContentPane().add(c255255204, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 20, 20));

        c204255204.setBackground(new java.awt.Color(204, 255, 204));
        c204255204.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c204255204ActionPerformed(evt);
            }
        });
        getContentPane().add(c204255204, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 20, 20));

        c1204255204.setBackground(new java.awt.Color(204, 255, 204));
        c1204255204.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1204255204ActionPerformed(evt);
            }
        });
        getContentPane().add(c1204255204, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 20, 20));

        c204204204.setBackground(new java.awt.Color(204, 204, 204));
        c204204204.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c204204204ActionPerformed(evt);
            }
        });
        getContentPane().add(c204204204, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 20, 20));

        c102255255.setBackground(new java.awt.Color(102, 255, 255));
        c102255255.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c102255255ActionPerformed(evt);
            }
        });
        getContentPane().add(c102255255, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 20, 20));

        c153153255.setBackground(new java.awt.Color(153, 153, 255));
        c153153255.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c153153255ActionPerformed(evt);
            }
        });
        getContentPane().add(c153153255, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 20, 20));

        c255153255.setBackground(new java.awt.Color(255, 153, 255));
        c255153255.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c255153255ActionPerformed(evt);
            }
        });
        getContentPane().add(c255153255, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 20, 20));

        c255102102.setBackground(new java.awt.Color(255, 102, 102));
        c255102102.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c255102102ActionPerformed(evt);
            }
        });
        getContentPane().add(c255102102, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, 20, 20));

        c255204153.setBackground(new java.awt.Color(255, 204, 153));
        c255204153.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c255204153ActionPerformed(evt);
            }
        });
        getContentPane().add(c255204153, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, 20, 20));

        c255255153.setBackground(new java.awt.Color(255, 255, 153));
        c255255153.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c255255153ActionPerformed(evt);
            }
        });
        getContentPane().add(c255255153, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, 20, 20));

        c102255102.setBackground(new java.awt.Color(102, 255, 102));
        c102255102.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c102255102ActionPerformed(evt);
            }
        });
        getContentPane().add(c102255102, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, 20, 20));

        c153255204.setBackground(new java.awt.Color(153, 255, 204));
        c153255204.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c153255204ActionPerformed(evt);
            }
        });
        getContentPane().add(c153255204, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 20, 20));

        c153153153.setBackground(new java.awt.Color(153, 153, 153));
        c153153153.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c153153153ActionPerformed(evt);
            }
        });
        getContentPane().add(c153153153, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 20, 20));

        c102204255.setBackground(new java.awt.Color(102, 204, 255));
        c102204255.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c102204255ActionPerformed(evt);
            }
        });
        getContentPane().add(c102204255, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 20, 20));

        c204102255.setBackground(new java.awt.Color(204, 102, 255));
        c204102255.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c204102255ActionPerformed(evt);
            }
        });
        getContentPane().add(c204102255, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 20, 20));

        c25551255.setBackground(new java.awt.Color(255, 51, 255));
        c25551255.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c25551255ActionPerformed(evt);
            }
        });
        getContentPane().add(c25551255, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 20, 20));

        c2555151.setBackground(new java.awt.Color(255, 51, 51));
        c2555151.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2555151ActionPerformed(evt);
            }
        });
        getContentPane().add(c2555151, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, 20, 20));

        c255153102.setBackground(new java.awt.Color(255, 153, 102));
        c255153102.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c255153102ActionPerformed(evt);
            }
        });
        getContentPane().add(c255153102, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, 20, 20));

        c255255102.setBackground(new java.awt.Color(255, 255, 102));
        c255255102.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c255255102ActionPerformed(evt);
            }
        });
        getContentPane().add(c255255102, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, 20, 20));

        c02550.setBackground(new java.awt.Color(0, 255, 0));
        c02550.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c02550ActionPerformed(evt);
            }
        });
        getContentPane().add(c02550, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 20, 20));

        c102255204.setBackground(new java.awt.Color(102, 255, 204));
        c102255204.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c102255204ActionPerformed(evt);
            }
        });
        getContentPane().add(c102255204, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, 20, 20));

        c102102102.setBackground(new java.awt.Color(102, 102, 102));
        c102102102.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c102102102ActionPerformed(evt);
            }
        });
        getContentPane().add(c102102102, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 20, 20));

        c051255.setBackground(new java.awt.Color(0, 51, 255));
        c051255.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c051255ActionPerformed(evt);
            }
        });
        getContentPane().add(c051255, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 20, 20));

        c2040204.setBackground(new java.awt.Color(204, 0, 204));
        c2040204.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2040204ActionPerformed(evt);
            }
        });
        getContentPane().add(c2040204, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 20, 20));

        c1530102.setBackground(new java.awt.Color(153, 0, 102));
        c1530102.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1530102ActionPerformed(evt);
            }
        });
        getContentPane().add(c1530102, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 20, 20));

        c255051.setBackground(new java.awt.Color(255, 0, 51));
        c255051.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c255051ActionPerformed(evt);
            }
        });
        getContentPane().add(c255051, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, 20, 20));

        c25515351.setBackground(new java.awt.Color(255, 153, 51));
        c25515351.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c25515351ActionPerformed(evt);
            }
        });
        getContentPane().add(c25515351, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, 20, 20));

        c25525551.setBackground(new java.awt.Color(255, 255, 51));
        c25525551.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c25525551ActionPerformed(evt);
            }
        });
        getContentPane().add(c25525551, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 500, 20, 20));

        c02040.setBackground(new java.awt.Color(0, 204, 0));
        c02040.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c02040ActionPerformed(evt);
            }
        });
        getContentPane().add(c02040, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, 20, 20));

        c0255204.setBackground(new java.awt.Color(0, 255, 204));
        c0255204.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c0255204ActionPerformed(evt);
            }
        });
        getContentPane().add(c0255204, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 500, 20, 20));

        c000.setBackground(new java.awt.Color(0, 0, 0));
        c000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c000ActionPerformed(evt);
            }
        });
        getContentPane().add(c000, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 20, 20));

        c051102.setBackground(new java.awt.Color(0, 51, 102));
        c051102.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c051102ActionPerformed(evt);
            }
        });
        getContentPane().add(c051102, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 20, 20));

        c1020102.setBackground(new java.awt.Color(102, 0, 102));
        c1020102.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1020102ActionPerformed(evt);
            }
        });
        getContentPane().add(c1020102, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 20, 20));

        c102051.setBackground(new java.awt.Color(102, 0, 51));
        c102051.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c102051ActionPerformed(evt);
            }
        });
        getContentPane().add(c102051, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, 20, 20));

        c204051.setBackground(new java.awt.Color(204, 0, 51));
        c204051.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c204051ActionPerformed(evt);
            }
        });
        getContentPane().add(c204051, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 520, 20, 20));

        c2041020.setBackground(new java.awt.Color(204, 102, 0));
        c2041020.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2041020ActionPerformed(evt);
            }
        });
        getContentPane().add(c2041020, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 520, 20, 20));

        c2552550.setBackground(new java.awt.Color(255, 255, 0));
        c2552550.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2552550ActionPerformed(evt);
            }
        });
        getContentPane().add(c2552550, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 520, 20, 20));

        c01530.setBackground(new java.awt.Color(0, 153, 0));
        c01530.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c01530ActionPerformed(evt);
            }
        });
        getContentPane().add(c01530, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 520, 20, 20));

        airBrush.setBackground(new java.awt.Color(0, 0, 0));
        Tools.add(airBrush);
        airBrush.setForeground(new java.awt.Color(255, 255, 255));
        airBrush.setText("Air Brush");
        getContentPane().add(airBrush, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        text.setBackground(new java.awt.Color(0, 0, 0));
        Tools.add(text);
        text.setForeground(new java.awt.Color(255, 255, 255));
        text.setText("Text");
        getContentPane().add(text, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        setBackground.setBackground(new java.awt.Color(0, 0, 0));
        setBackground.setForeground(new java.awt.Color(255, 255, 255));
        setBackground.setText("Set background");
        getContentPane().add(setBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simplepaint/resource/Background.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 550));

        jMenuBar1.setBackground(new java.awt.Color(102, 102, 102));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));

        jMenu1.setText("File");

        MenuNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        MenuNew.setText("New");
        MenuNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuNewActionPerformed(evt);
            }
        });
        jMenu1.add(MenuNew);

        MenuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        MenuExit.setText("Exit");
        MenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuExitActionPerformed(evt);
            }
        });
        jMenu1.add(MenuExit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        getAccessibleContext().setAccessibleName("jbutton5");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void paintPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paintPanelMousePressed
        // TODO add your handling code here:
        mouseX=evt.getX();
        mouseY=evt.getY();
    }//GEN-LAST:event_paintPanelMousePressed

    private void paintPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paintPanelMouseDragged
        // TODO add your handling code here:
        movX=evt.getX();
        movY=evt.getY();
        if(Pencil.isSelected()){
            if(g!= null){
                g.setStroke(new BasicStroke(size));
                g.drawLine(mouseX, mouseY, movX, movY);      
            }
            mouseX = movX;
            mouseY = movY;
        }
        if(Eraser.isSelected()){
            if(g!= null){
                g.setColor(g.getColor());
                g.setStroke(new BasicStroke(size));
                g.fillOval(mouseX, mouseY,eraserRadius,eraserRadius);      
            }
            mouseX = movX;
            mouseY = movY;
        }
        if(airBrush.isSelected()){
            if(g!= null){
                g.setStroke(new BasicStroke(size));
                g.drawString(". . ", mouseX, mouseY);
                g.drawString(". . . ", mouseX+10, mouseY-5);
                g.drawString(". . ", mouseX+20, mouseY);
            }
            mouseX = movX;
            mouseY = movY;
        }
            
    }//GEN-LAST:event_paintPanelMouseDragged

    private void paintPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paintPanelMouseReleased
        // TODO add your handling code here:
        /*Dimension d;
        d=paintPanel.getSize();
        int refX=854-d.width;
        int refY=554-d.height;*/
        movX=evt.getX();
        movY=evt.getY();
     
        if(Line.isSelected()){
            if(g!= null){
                g.setStroke(new BasicStroke(size));
                g.drawLine(mouseX, mouseY, movX, movY);
        }
        }
        if(Circle.isSelected()){
            if(g!=null){
                g.setStroke(new BasicStroke(size));
                g.drawOval(mouseX,mouseY,Math.abs(mouseX-movX),Math.abs(mouseX-movX));
        }
        }
        if(Rectangle.isSelected()){
            if(g!=null){
                g.setStroke(new BasicStroke(size));
                g.drawRect(mouseX, mouseY, Math.abs(mouseX-movX),Math.abs(mouseY-movY));
        }
        }
        if(Oval.isSelected()){
            if(g!=null){
                g.setStroke(new BasicStroke(size));
                g.drawOval(mouseX, mouseY,Math.abs(mouseX-movX),Math.abs(mouseY-movY));
        }
        }    
        if(FillCircle.isSelected()){
            if(g!=null){
                g.setStroke(new BasicStroke(size));
                g.fillOval(mouseX,mouseY,Math.abs(mouseX-movX),Math.abs(mouseX-movX));
        }
        }
        if(FillRectangle.isSelected()){
            if(g!=null){
                g.setStroke(new BasicStroke(size));
                g.fillRect(mouseX, mouseY, Math.abs(mouseX-movX),Math.abs(mouseY-movY));
        }
        }
        if(FillOval.isSelected()){
            if(g!=null){
                g.setStroke(new BasicStroke(size));
                g.fillOval(mouseX, mouseY,Math.abs(mouseX-movX),Math.abs(mouseY-movY));
                }
        } 
        if(text.isSelected()){
            if(g!=null){
                JTextField j=new JTextField();
                j.setBounds(mouseX, mouseY, Math.abs(mouseX-movX),Math.abs(mouseY-movY));
                paintPanel.add(j);
                paintPanel.validate();
                j.setVisible(true);
            }
        }
        /*if(setBackground.isSelected()){
            if(g!=null){
                paintPanel.setColor(g.getColor());
            }
        }*/
    }//GEN-LAST:event_paintPanelMouseReleased

    private void BrushSizeValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_BrushSizeValueChanged
        // TODO add your handling code here:
        if(BrushSize.getSelectedIndex()==0){
            eraserRadius=5;
            size=1;}
        else if(BrushSize.getSelectedIndex()==1){
            eraserRadius=7;
            size=2;}
        else if(BrushSize.getSelectedIndex()==2){
            eraserRadius=10;
            size=3;}
        else if(BrushSize.getSelectedIndex()==3){
            eraserRadius=15;
            size=4;}
        else if(BrushSize.getSelectedIndex()==4){
            eraserRadius=20;
            size=5;}
        
    }//GEN-LAST:event_BrushSizeValueChanged

    private void c204204255ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c204204255ActionPerformed
        // TODO add your handling code here:
        g.setColor(c204204255.getBackground());      
    }//GEN-LAST:event_c204204255ActionPerformed

    private void c204255255ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c204255255ActionPerformed
        // TODO add your handling code here:
        g.setColor(c204255255.getBackground());
    }//GEN-LAST:event_c204255255ActionPerformed

    private void c0204204ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c0204204ActionPerformed
        // TODO add your handling code here:
        g.setColor(c0204204.getBackground());
    }//GEN-LAST:event_c0204204ActionPerformed

    private void c255255255ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c255255255ActionPerformed
        // TODO add your handling code here:
        g.setColor(c255255255.getBackground());
    }//GEN-LAST:event_c255255255ActionPerformed

    private void c255204255ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c255204255ActionPerformed
        // TODO add your handling code here:
        g.setColor(c255204255.getBackground());
    }//GEN-LAST:event_c255204255ActionPerformed

    private void c255204204ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c255204204ActionPerformed
        // TODO add your handling code here:
        g.setColor(c255204204.getBackground());
    }//GEN-LAST:event_c255204204ActionPerformed

    private void c1255204204ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1255204204ActionPerformed
        // TODO add your handling code here:
        g.setColor(c1255204204.getBackground());
    }//GEN-LAST:event_c1255204204ActionPerformed

    private void c255255204ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c255255204ActionPerformed
        // TODO add your handling code here:
        g.setColor(c255255204.getBackground());
    }//GEN-LAST:event_c255255204ActionPerformed

    private void c204255204ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c204255204ActionPerformed
        // TODO add your handling code here:
        g.setColor(c204255204.getBackground());
    }//GEN-LAST:event_c204255204ActionPerformed

    private void c1204255204ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1204255204ActionPerformed
        // TODO add your handling code here:
        g.setColor(c1204255204.getBackground());
    }//GEN-LAST:event_c1204255204ActionPerformed

    private void c204204204ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c204204204ActionPerformed
        // TODO add your handling code here:
        g.setColor(c204204204.getBackground());
    }//GEN-LAST:event_c204204204ActionPerformed

    private void c102255255ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c102255255ActionPerformed
        // TODO add your handling code here:
        g.setColor(c102255255.getBackground());
    }//GEN-LAST:event_c102255255ActionPerformed

    private void c153153255ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c153153255ActionPerformed
        // TODO add your handling code here:
        g.setColor(c153153255.getBackground());
    }//GEN-LAST:event_c153153255ActionPerformed

    private void c255153255ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c255153255ActionPerformed
        // TODO add your handling code here:
        g.setColor(c255153255.getBackground());
    }//GEN-LAST:event_c255153255ActionPerformed

    private void c255102102ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c255102102ActionPerformed
        // TODO add your handling code here:
        g.setColor(c255102102.getBackground());
    }//GEN-LAST:event_c255102102ActionPerformed

    private void c255204153ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c255204153ActionPerformed
        // TODO add your handling code here:
        g.setColor(c255204153.getBackground());
    }//GEN-LAST:event_c255204153ActionPerformed

    private void c255255153ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c255255153ActionPerformed
        // TODO add your handling code here:
        g.setColor(c255255153.getBackground());
    }//GEN-LAST:event_c255255153ActionPerformed

    private void c102255102ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c102255102ActionPerformed
        // TODO add your handling code here:
        g.setColor(c102255102.getBackground());
    }//GEN-LAST:event_c102255102ActionPerformed

    private void c153255204ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c153255204ActionPerformed
        // TODO add your handling code here
        g.setColor(c153255204.getBackground());
    }//GEN-LAST:event_c153255204ActionPerformed

    private void c153153153ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c153153153ActionPerformed
        // TODO add your handling code here:
        g.setColor(c153153153.getBackground());
    }//GEN-LAST:event_c153153153ActionPerformed

    private void c102204255ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c102204255ActionPerformed
        // TODO add your handling code here:
        g.setColor(c102204255.getBackground());
    }//GEN-LAST:event_c102204255ActionPerformed

    private void c204102255ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c204102255ActionPerformed
        // TODO add your handling code here:
        g.setColor(c204102255.getBackground());
    }//GEN-LAST:event_c204102255ActionPerformed

    private void c25551255ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c25551255ActionPerformed
        // TODO add your handling code here:
        g.setColor(c25551255.getBackground());
    }//GEN-LAST:event_c25551255ActionPerformed

    private void c2555151ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2555151ActionPerformed
        // TODO add your handling code here:
        g.setColor(c2555151.getBackground());
    }//GEN-LAST:event_c2555151ActionPerformed

    private void c255153102ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c255153102ActionPerformed
        // TODO add your handling code here:
        g.setColor(c255153102.getBackground());
    }//GEN-LAST:event_c255153102ActionPerformed

    private void c255255102ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c255255102ActionPerformed
        // TODO add your handling code here:
        g.setColor(c255255102.getBackground());
    }//GEN-LAST:event_c255255102ActionPerformed

    private void c02550ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c02550ActionPerformed
        // TODO add your handling code here:
        g.setColor(c02550.getBackground());
    }//GEN-LAST:event_c02550ActionPerformed

    private void c102255204ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c102255204ActionPerformed
        // TODO add your handling code here:
        g.setColor(c102255204.getBackground());
    }//GEN-LAST:event_c102255204ActionPerformed

    private void c102102102ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c102102102ActionPerformed
        // TODO add your handling code here:
        g.setColor(c102102102.getBackground());
    }//GEN-LAST:event_c102102102ActionPerformed

    private void c051255ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c051255ActionPerformed
        // TODO add your handling code here:
        g.setColor(c051255.getBackground());
    }//GEN-LAST:event_c051255ActionPerformed

    private void c2040204ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2040204ActionPerformed
        // TODO add your handling code here:
        g.setColor(c2040204.getBackground());
    }//GEN-LAST:event_c2040204ActionPerformed

    private void c1530102ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1530102ActionPerformed
        // TODO add your handling code here:
        g.setColor(c1530102.getBackground());
    }//GEN-LAST:event_c1530102ActionPerformed

    private void c255051ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c255051ActionPerformed
        // TODO add your handling code here:
        g.setColor(c255051.getBackground());
    }//GEN-LAST:event_c255051ActionPerformed

    private void c25515351ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c25515351ActionPerformed
        // TODO add your handling code here:
        g.setColor(c25515351.getBackground());
    }//GEN-LAST:event_c25515351ActionPerformed

    private void c25525551ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c25525551ActionPerformed
        // TODO add your handling code here:
        g.setColor(c25525551.getBackground());
    }//GEN-LAST:event_c25525551ActionPerformed

    private void c02040ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c02040ActionPerformed
        // TODO add your handling code here:
        g.setColor(c02040.getBackground());
    }//GEN-LAST:event_c02040ActionPerformed

    private void c0255204ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c0255204ActionPerformed
        // TODO add your handling code here:
        g.setColor(c0255204.getBackground());
    }//GEN-LAST:event_c0255204ActionPerformed

    private void c000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c000ActionPerformed
        // TODO add your handling code here:
        g.setColor(c000.getBackground());
    }//GEN-LAST:event_c000ActionPerformed

    private void c051102ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c051102ActionPerformed
        // TODO add your handling code here:
        g.setColor(c051102.getBackground());
    }//GEN-LAST:event_c051102ActionPerformed

    private void c1020102ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1020102ActionPerformed
        // TODO add your handling code here:
        g.setColor(c1020102.getBackground());
    }//GEN-LAST:event_c1020102ActionPerformed

    private void c102051ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c102051ActionPerformed
        // TODO add your handling code here:
        g.setColor(c102051.getBackground());
    }//GEN-LAST:event_c102051ActionPerformed

    private void c204051ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c204051ActionPerformed
        // TODO add your handling code here:
        g.setColor(c204051.getBackground());
    }//GEN-LAST:event_c204051ActionPerformed

    private void c2041020ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2041020ActionPerformed
        // TODO add your handling code here:
        g.setColor(c2041020.getBackground());
    }//GEN-LAST:event_c2041020ActionPerformed

    private void c2552550ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2552550ActionPerformed
        // TODO add your handling code here:
        g.setColor(c2552550.getBackground());
    }//GEN-LAST:event_c2552550ActionPerformed

    private void c01530ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c01530ActionPerformed
        // TODO add your handling code here:
        g.setColor(c01530.getBackground());
    }//GEN-LAST:event_c01530ActionPerformed

    private void MenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_MenuExitActionPerformed

    private void MenuNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuNewActionPerformed
        // TODO add your handling code here:
        repaint();
    }//GEN-LAST:event_MenuNewActionPerformed
    int max(int a,int b)
    {
        if(a>b)
            return a;
        return b;
    }
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaintWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaintWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaintWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaintWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        java.awt.EventQueue.invokeLater(() -> {
            
            new PaintWindow().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList BrushSize;
    private javax.swing.JRadioButton Circle;
    private javax.swing.JRadioButton Eraser;
    private javax.swing.JRadioButton FillCircle;
    private javax.swing.JRadioButton FillOval;
    private javax.swing.JRadioButton FillRectangle;
    private javax.swing.JRadioButton Line;
    private javax.swing.JMenuItem MenuExit;
    private javax.swing.JMenuItem MenuNew;
    private javax.swing.JRadioButton Oval;
    private javax.swing.JRadioButton Pencil;
    private javax.swing.JRadioButton Rectangle;
    private javax.swing.ButtonGroup Tools;
    private javax.swing.JRadioButton airBrush;
    private javax.swing.JButton c000;
    private javax.swing.JButton c01530;
    private javax.swing.JButton c02040;
    private javax.swing.JButton c0204204;
    private javax.swing.JButton c02550;
    private javax.swing.JButton c0255204;
    private javax.swing.JButton c051102;
    private javax.swing.JButton c051255;
    private javax.swing.JButton c1020102;
    private javax.swing.JButton c102051;
    private javax.swing.JButton c102102102;
    private javax.swing.JButton c102204255;
    private javax.swing.JButton c102255102;
    private javax.swing.JButton c102255204;
    private javax.swing.JButton c102255255;
    private javax.swing.JButton c1204255204;
    private javax.swing.JButton c1255204204;
    private javax.swing.JButton c1530102;
    private javax.swing.JButton c153153153;
    private javax.swing.JButton c153153255;
    private javax.swing.JButton c153255204;
    private javax.swing.JButton c2040204;
    private javax.swing.JButton c204051;
    private javax.swing.JButton c2041020;
    private javax.swing.JButton c204102255;
    private javax.swing.JButton c204204204;
    private javax.swing.JButton c204204255;
    private javax.swing.JButton c204255204;
    private javax.swing.JButton c204255255;
    private javax.swing.JButton c255051;
    private javax.swing.JButton c255102102;
    private javax.swing.JButton c255153102;
    private javax.swing.JButton c255153255;
    private javax.swing.JButton c25515351;
    private javax.swing.JButton c255204153;
    private javax.swing.JButton c255204204;
    private javax.swing.JButton c255204255;
    private javax.swing.JButton c2552550;
    private javax.swing.JButton c255255102;
    private javax.swing.JButton c255255153;
    private javax.swing.JButton c255255204;
    private javax.swing.JButton c255255255;
    private javax.swing.JButton c25525551;
    private javax.swing.JButton c25551255;
    private javax.swing.JButton c2555151;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel paintPanel;
    private javax.swing.JRadioButton setBackground;
    private javax.swing.JRadioButton text;
    // End of variables declaration//GEN-END:variables
}
